travis:
  secure:
    BINSTAR_TOKEN: bgLkUnr049Djcr5pB/celYnWj+Z1RMpTFeYR/3hBqch3ZEb7mlBi8x0IarJDPCbmbmjpjMfres4/ikle/5zL54+9aq3DQdM8RHTJHfl4QpTnqWf50t2I7Fr3mz1vpOrCI9rfLzuynVIu4CB45AZ2ZtAI7dga6OUuePOYh0uGV4rxYkVBTH6yxkLp7xEuqdiM9xLAgdXJmbByvPmGXMpMy8UkIrIL1rEOxwu0FMyrluBisYCu4yWn/ROj7AE+Blyd3WKwDOkcgVng3+4bfF2DwKjp3dWmEGNO0ktXTkjubb1AyHJjDi4e0hU9l0s0yLoiX1CQ9F+arr4akTEf2JYRmK+KK54VWT1eZsYyoZTZAiZMzhLiAUsJKT7wfBy0QmoG/ab6575xSBoai4eXxsKV5PoSwwm38YTtGwY3G7+Y1QaS6/2HtbAkeqsdKLi5xDLW/1IIc5bnqx6NzXFZg/7MET0ox+nFPSztroOzLTbHItGWAmR2jrh12OXpy5wD800G7ySWrtG6xalOevujFFaO3BIomE7R2LtP0HZglL21HAqoqCQa1ztSIGffmg1n0N/owbmb/2xy1cIqQy785PAZonvxoxi2DG393BKhbDNttt/J/TFjrStBHHkt4erzzoWlpNA5V3kyTi+fJSt0+YoAQ0neSD7VX0sG454GDqzeHuo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
