travis:
  secure:
    BINSTAR_TOKEN: uLYmjZWu9YPFIpA20G5Q0CNu1CbPfMut6hrUMdWLEaeHBASLTv+RYAudJFalgiQZh6zVJ6bBPdW253zysz9vAoIrQj2hl27+jEvfVkS/qZxQiDW64MTaZK0rAaoQdWd70J5k92ZVcSR4trw2QszpxAOoqYzTUWKY8/YjEBOPBlCfUgSuG6n7V8/OWjMBjbI9+n4aCHpIao4oEijrNOnaBejbVqWV69XFfPZNR1AArAzc8eFmChGuLP6tWZqJGOsI9DBOivNQsN+wE2k8BFRwL1L8sOVWnKikJOZ7f7YBcwgpq9pDgNWs3VWMqXsXkg2Ct6G3sKRqubZCiKJ3/ufIo1mJjwz8Az1nlt6mUfHKvDlR5Uc6WGYRdikPMxEgmikKm896RYQ3fcjYT/GA2EYGOzbdpd8vNmZsGePpHjcFWeCBWTT7lUywCqyNydWWEYdtk7Fdol08gP3tVpu/9+lgdO7JV0P60py7m5snJ0lSEOQzSkDVw5P5btrnq3Y5pIXRXHffwbMhvFdg4Axy2YHLSFvT5I2gduQnFuWzVzSfUdr8ZmWQRiG8zzTJjbpf59YqNt9RQZzets00NxG0mukl28qAxKcfEby9zm1u3JiWpDe2uJpLE/QdSzBuMOSmFrSztljrj//9adWJLoMD1IsVzBBGstQDVvm+6N9TGIaHWeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
